### PR TITLE
Python

### PR DESCRIPTION
**Pull request by bastie**
add support for language parameters in Python

### CODE REVIEW

**Comment by MCFreddie777** [comment]
Wonderful change! Any idea when this'll be released?

**Comment by bastie** [comment]
> Wonderful change! Any idea when this'll be released?

In result to make same change in Java and .net, maybe end of week.

**Comment by MCFreddie777** [comment]
I'm really happy of it. It allows us to use multiple instances in parallel without interfering (compared to using env variables). Thank you.

**Comment by bastie** [comment]
> I'm really happy of it. It allows us to use multiple instances in parallel without interfering (compared to using env variables). Thank you.

In addition you can create a `config_sv.properties`  😉

**Pull request merged**
